 mysqldb:
    container_name: mysqldb
    image: mysql:8
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_volume:/var/lib/mysql
  spring_app:
    image: tpachat
    container_name: tpachat
    restart: on-failure
    ports:
      - 8090:8089
    depends_on:
      - mysqldb
volumes:
 mysql_volume:
   external: true
